import { DEV_SEED_VEHICLES_IDS } from "src/database/typeorm-seeds/workspace/vehicles";

export const VEHICLE_DATA_SEEDS = [
  {
    id: DEV_SEED_VEHICLES_IDS.v1,
    name: 'Chevrolet Sonic 2012',
    // dealershipId: DEV_SEED_DEALERSHIP_IDS.FL154,
    locationId: 'FL154',
    dataType: 'INVENTORY#8912082',
    capacity: 5,
    cityMpg: 25,
    defaultImage: 'https://jdbycdn.azureedge.net/Default/0.png',
    defaultMdImage: '',
    defaultSmImage: '',
    displacement: '1.8L',
    doorCount: 4,
    driveType: 'FWD',
    exteriorColor: 'Silver Ice Metallic',
    fuelType: 'Gasoline Fuel',
    hasImages: false,
    hwyMpg: 35,
    imageCount: 0,
    imageUrls: ['https://jdbycdn.azureedge.net/Default/0.png'],
    interiorColor: 'Jet Black/Dark Titanium',
    isWorking: true,
    KeyFeatures: ['Auto transmission', 'Great MPG', 'Keyless Entry'],
    make: 'Chevrolet',
    marketClass: '4-door Compact Passenger Car',
    miles: 106715,
    model: 'Sonic',
    modifiedDate: '2025-03-06T00:00:00Z',
    noOfCylinders: 4,
    noOfSpeeds: 6,
    priceInDollars: 0,
    stockNumber: 8912082,
    style: 'Car',
    SubModel: 'LS',
    transmission: '6-Speed Automatic',
    transmissionType: 'Automatic',
    VehicleDescription: [
      'Expert Reviews! As reported by KBB.com: In sedan or 5-door hatchback configuration, the 2012 Chevy Sonic is the quietest and most composed subcompact car you can buy. Combined with more conventional styling than some of its key competitors, the Sonic is destined to become a mass-market favorite.',
      'IIHS Top Safety Pick. Only 95,600 miles! Scores 35 Highway MPG and 25 City MPG! This Chevrolet Sonic boasts a Gas I4 1.8L/110 engine powering this Automatic transmission. TRANSMISSION, AUTOMATIC (STD), SILVER ICE METALLIC, SEATS, FRONT BUCKET WITH RECLINE AND HEIGHT-ADJUSTABLE HEADRESTS (STD).',
      'Stop By Today A short visit to Byrider - FL154 located at 7701 Park Blvd, Pinellas Park, IN 33781 can get you a tried-and-true Sonic today!',
      'The Votes are Counted IIHS Top Safety Pick, KBB.com 10 Coolest New Cars Under $18,000.',
      'This Chevrolet Sonic Comes Equipped with These Options JET BLACK/DARK TITANIUM, SPORT CLOTH SEAT TRIM, ENGINE, ECOTEC 1.8L VARIABLE VALVE TIMING DOHC 4-CYLINDER SEQUENTIAL MFI estimated (138 hp [103 kW] @ 6300 rpm, 125 lb-ft of torque [168.8 N-m] @ 3800 rpm) (STD), AUDIO SYSTEM, AM/FM STEREO WITH EQUALIZER digital clock and auxiliary input jack (STD), 2LS PREFERRED EQUIPMENT GROUP includes Standard Equipment, Wipers, front intermittent, variable, Windows, manual, Wheels, 15" (38.1 cm) painted aluminum, Visors, driver and front passenger vanity mirrors, covered, Trunk emergency release handle, transmission, automatic.',
    ],
    vehicleType: 'sedan',
    vin: '1G1JA5SH9C4144654',
    year: 2012,
  },
  {
    id: DEV_SEED_VEHICLES_IDS.v2,
    name: 'Ford Taurus 2013' ,
    // dealershipId: DEV_SEED_DEALERSHIP_IDS.FL154,
    locationId: 'FL154',
    dataType: 'INVENTORY#8924365',
    capacity: 5,
    cityMpg: 19,
    defaultImage: 'https://jdbycdn.azureedge.net/8924365/1.jpg',
    defaultMdImage: 'https://jdbycdn.azureedge.net/8924365/1-md.jpg',
    defaultSmImage: 'https://jdbycdn.azureedge.net/8924365/1-sm.jpg',
    displacement: '3.5L',
    doorCount: 4,
    driveType: 'FWD',
    exteriorColor: 'Green',
    fuelType: 'Gasoline Fuel',
    hasImages: true,
    hwyMpg: 29,
    imageCount: 7,
    imageUrls: [],
    isWorking: true,
    KeyFeatures: [],
    make: 'Ford',
    marketClass: '4-door Large Passenger Car',
    miles: 164307,
    model: 'Taurus',
    modifiedDate: '2025-02-06T00:00:00Z',
    noOfCylinders: 6,
    noOfSpeeds: 6,
    priceInDollars: 0,
    stockNumber: 8924365,
    style: 'Car',
    SubModel: 'SEL',
    transmission: '6-Speed Automatic w/Manual Shift',
    transmissionType: 'Automatic',
    VehicleDescription: [],
    vehicleType: 'sedan',
    vin: '1FAHP2E8XDG109383',
    year: 2013,
  },
  {
    id: DEV_SEED_VEHICLES_IDS.v3,
    name: 'Volkswagen Jetta Sedan 2012',
    locationId: 'FL154',
    // dealershipId: DEV_SEED_DEALERSHIP_IDS.FL154,
    dataType: 'INVENTORY#8938314',
    capacity: 5,
    cityMpg: 24,
    defaultImage: 'https://jdbycdn.azureedge.net/8938314/1.jpg',
    defaultMdImage: 'https://jdbycdn.azureedge.net/8938314/1-md.jpg',
    defaultSmImage: 'https://jdbycdn.azureedge.net/8938314/1-sm.jpg',
    displacement: '2.5L',
    doorCount: 4,
    driveType: 'FWD',
    exteriorColor: 'Gray',
    fuelType: 'Gasoline Fuel',
    hasImages: true,
    hwyMpg: 32,
    imageCount: 7,
    imageUrls: [],
    isWorking: true,
    KeyFeatures: [],
    make: 'Volkswagen',
    marketClass: '4-door Compact Passenger Car',
    miles: 101335,
    model: 'Jetta Sedan',
    modifiedDate: '2025-02-26T00:00:00Z',
    noOfCylinders: 5,
    noOfSpeeds: 6,
    priceInDollars: 0,
    stockNumber: 8938314,
    style: 'Car',
    transmission: '6-Speed Automatic w/manual shift',
    transmissionType: 'Automatic',
    VehicleDescription: [],
    vehicleType: 'sedan',
    vin: '3VWDP7AJ4CM300202',
    year: 2012,
  },
  {
    id: DEV_SEED_VEHICLES_IDS.v4,
    name:'Kia Sorento 2015', 
    locationId: 'KY111',
    // dealershipId: DEV_SEED_DEALERSHIP_IDS.KY111,
    dataType: 'INVENTORY#8903506',
    capacity: 5,
    cityMpg: 20,
    defaultImage: 'https://jdbycdn.azureedge.net/8903506/1.jpg',
    defaultMdImage: 'https://jdbycdn.azureedge.net/8903506/1-md.jpg',
    defaultSmImage: 'https://jdbycdn.azureedge.net/8903506/1-sm.jpg',
    displacement: '2.4 L',
    doorCount: 4,
    driveType: 'FWD',
    exteriorColor: 'Ebony Black',
    fuelType: 'Gasoline Fuel',
    hasImages: true,
    hwyMpg: 27,
    imageCount: 20,
    imageUrls: [],
    interiorColor: 'Gray',
    isWorking: true,
    make: 'Kia',
    marketClass: '2WD Sport Utility Vehicles',
    model: 'Sorento',
    modifiedDate: '2024-05-07T00:00:00Z',
    noOfCylinders: 4,
    noOfSpeeds: 6,
    priceInDollars: 16995,
    stockNumber: 8903506,
    style: 'Sport Utility',
    SubModel: 'LX',
    transmission: '6-Speed Automatic w/OD',
    transmissionType: 'Automatic',
    vehicleType: 'suv',
    vin: '5XYKT3A6XFG568117',
    year: 2015,
  },
  {
    id: DEV_SEED_VEHICLES_IDS.v5,
    name: 'Chevrolet Imapala Limited 2014', 
    locationId: 'KY111',
    // dealershipId: DEV_SEED_DEALERSHIP_IDS.KY111,
    dataType: 'INVENTORY#8944308',
    capacity: 5,
    cityMpg: 18,
    defaultImage: 'https://jdbycdn.azureedge.net/8944308/1.jpg',
    defaultMdImage: 'https://jdbycdn.azureedge.net/8944308/1-md.jpg',
    defaultSmImage: 'https://jdbycdn.azureedge.net/8944308/1-sm.jpg',
    displacement: '3.6L',
    doorCount: 4,
    driveType: 'FWD',
    exteriorColor: 'Black',
    fuelType: 'Gasoline Fuel',
    hasImages: true,
    hwyMpg: 30,
    imageCount: 17,
    imageUrls: [],
    interiorColor: 'Gray',
    isWorking: true,
    make: 'Chevrolet',
    marketClass: '4-door Large Passenger Car',
    miles: 129651,
    model: 'Impala Limited',
    modifiedDate: '2025-01-21T00:00:00Z',
    noOfCylinders: 6,
    noOfSpeeds: 6,
    priceInDollars: 17395,
    stockNumber: 8944308,
    style: '4dr Car',
    SubModel: 'LT',
    transmission: '6-Speed Automatic',
    transmissionType: 'Automatic',
    vehicleType: 'sedan',
    vin: '2G1WB5E39E1135034',
    year: 2014,
  },
];
